---
apiVersion: apps/v1
kind: Deployment
metadata:
#  name: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ template "mongodb.fullname" . }}
  labels:
    app: search
    component: mongodb
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
      component: mongodb
      release: {{ .Release.Name }}
  template:
    metadata:
      name: mongodb
      labels:
        app: search
        component: mongodb
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mongodb
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: mongodb
          protocol: TCP
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: {{ template "mongodb.fullname" . }}